
- name: add certbot repository
  apt_repository:
    repo: ppa:certbot/certbot
- name: Update cache
  apt:
    update_cache: yes
- name: Install certbot
  apt: 
    pkg: python-certbot-nginx 
    state: latest
- name: Get and Install the certificate
  shell:
    cmd: certbot --nginx -n --agree-tos --email youremail@domain.com -d www.your_domain.com -d your_domain.com        #-n flag is used for non interactive mode, meaning it will never ask the user for input
                                                                                                                      #--agree-tos flag is used to agree to the tos and is required when using -n 
                                                                                                                      #--email flag is required when using -n flag
                                                                                                                      #-d Refers to the domain to apply the ssl certificate can be used more than once for multiple domains 
